In [ ]:
import torch

torch.tensor(torch.randn(1, 2, 3)).scatter_(dim=1, index=torch.tensor([[0, 1, 0]]), src=torch.tensor([[1, 2, 3]]))

TypeError: tensor() missing 1 required positional arguments: "data"

In [1]:
import torch

g:\software\anaconda\envs\pytorch\Lib\site-packages\torch\cuda\__init__.py:65: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]


In [6]:
t = torch.full((3,2), 4)

In [7]:
t.size()

torch.Size([3, 2])

In [8]:
t.any(dim=1)

tensor([True, True, True])

In [37]:
completion_ids = torch.tensor([[1, 7, 3, 4], [5, 6, 7, 8], [1,2,3,4]])
eos_token_id = 7

In [30]:
is_eos = completion_ids == eos_token_id
is_eos

tensor([[False,  True, False, False],
        [False, False,  True, False],
        [False, False, False, False]])

In [31]:
eos_idx = torch.full((is_eos.size(0),), is_eos.size(1), dtype=torch.long, device=completion_ids.device)
eos_idx

tensor([4, 4, 4])

In [32]:
mask_exists = is_eos.any(dim=1)
mask_exists

tensor([ True,  True, False])

In [36]:
is_eos.int().argmax(dim=1)

tensor([1, 2, 0])

In [33]:
eos_idx[mask_exists] = is_eos.int().argmax(dim=1)[mask_exists]
eos_idx

tensor([1, 2, 4])

In [34]:
sequence_indices = torch.arange(is_eos.size(1), device=completion_ids.device).expand(is_eos.size(0), -1)
sequence_indices

tensor([[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]])

In [35]:
(sequence_indices <= eos_idx.unsqueeze(1)).int()

tensor([[1, 1, 0, 0],
        [1, 1, 1, 0],
        [1, 1, 1, 1]], dtype=torch.int32)

In [38]:
[i for i in ['a','b','c']for _ in range(3)]

['a', 'a', 'a', 'b', 'b', 'b', 'c', 'c', 'c']